on:
  push:
    branches:
      - main
name: ğŸš€ Deploy Production
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v1
      - name: Deploy Production server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "./menuOnline-frontend/"
          SCRIPT_BEFORE: |
            #!/bin/bash    
            cd menuOnline-frontend;
            rm -rf node_modules;
            rm -rf .env;
            make stop;
            docker rm -vf app_frontend;
            docker rmi -f $(docker images -q | grep -v app_frontend);                
          SCRIPT_AFTER: |     
            #!/bin/bash    
            cd menuOnline-frontend;
            echo "${{ vars.VAR_BUILD }}" | sed 's/ \+/\n/g' > .env;
            make build;